config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  

  get 'mis-compras/', to: "purchase#index"

  get 'checkout/', to: "checkout#index"
  get 'cart/', to: "cart#index"
  post 'payment/card'
  get 'payment/card'
  post 'payment/paypal'
  post 'payment/oxxo'
  resources :orders
  resources :cart_items
  namespace :admin do
    root 'welcome#index'
    resources :categories
    resources :products
    resources :brands
  end

  resources :categories
  resources :products
  resources :brands
  root 'welcome#index'

  # Namespace for the API

  # Api with subdomain, api.mysite.org as '/...'
    # namespace :api,
    #   defaults: { format: :json }, constraints: { subdomain: 'api' }, path: '/'  do
    # end

  # Api uri formated mysite.org/api/...
  namespace :api, defaults: { format: :json } do
    scope module: :v1,
              constraints: ApiConstraints.new(version: 1, default: true) do
      # We are going to list our resources here
    end
  end

  # Change path to '/' if you want direct access to users views
   # Device acces for the users
  devise_for :users, path: '/', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    unlocks: 'users/unlocks',
    omniauth: 'users/omniauth'
  }

  #spanish path for devise
  devise_scope :user do
    get 'iniciar-sesion', to: 'users/sessions#new'
    get 'cerrar-sesion', to: 'users/sessions#destroy', as: :sign_out

    get 'registro', to: 'users/registrations#new'
    post 'sign_up', to: 'users/registrations#create'

    get 'recuperar-contraseña', to: 'users/passwords#new'
    get 'recuperar-contrasena', to: 'users/passwords#new'
    get 'nueva-contraseña', to: 'users/passwords#edit'
    get 'nueva-contrasena', to: 'users/passwords#new'

    get 'solicitar-confirmacion', to: 'users/confirmations#new'
    get 'confirmar-cuenta', to: 'users/confirmations#show'
  end

end

app/models/brand.rb
class Brand < ApplicationRecord
	
	has_many :products
end

app/controllers/admin/brands_controller.rb
class Admin::BrandsController < Admin::BaseController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  @text  = ""
  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.all.paginate(:page => params[:page], :per_page => 15)
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
    @text  = "Agregar Marca"
  end

  # GET /brands/1/edit
  def edit
    @text  = "Editar"
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.require(:brand).permit(:name)
    end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.all
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.require(:brand).permit(:name)
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/admin/brands/_form.html.erb
<%= form_for([:admin,brand]) do |f| %>
  <% if brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
      <% brand.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, "Nombre" %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="actions">
      <%= f.submit @text, class: "btn btn-raised btn-info"%>
    </div>
<% end %>

app/views/admin/brands/edit.html.erb
<div class="row">
        <div class="col-md-10">
            <div class="card padding-largo">
                <div class="row">
                    <h3>Editar Marca</h3>
                </div>
                <div class="row">
                    <%= render 'form',  brand: @brand %>
                </div>
                <div class="row">
                    <%= link_to 'Regresar', admin_brands_path %>
                </div>
            </div>
        </div>
    </div>
    
    

app/views/admin/brands/index.html.erb
<div class="row">
    <div class="col-md-12">
      <div class="padding-largo">
        
        <div class="panel panel-info custom-panel">
        <div class="panel-heading">
          <h3 class="panel-title">Lista de marcas</h3>
        </div>
        <div class="panel-body">
          <table class="table table-striped table-hover">
            <thead></thead>
            <tbody>
              <%@brands.each do |p|%>
                <tr>
                  <td>
                    <%=p.name%>
                  </td>
  
                  <td>
                  <%= link_to 'Editar', edit_admin_brand_path(p) %>
                  <%= link_to 'Eliminar', admin_brand_path(p), method: :delete, data: { confirm: '¿Estas seguro de eliminarlo?' } %></td>
  
                </tr>
              <%end%>
            </tbody>
          </table>
  
          <div class="row">
            <div class="" style="margin: 0 auto;">
            <%= will_paginate @brands, renderer: BootstrapPagination::Rails  %>
          </div>
          </div>
        </div>
      </div>
  
      </div>
    </div>
  </div>
  
  
  <div class="float-btn">
    <a href="/admin/categories/new" class="btn btn-info btn-fab accent-color" data-toggle="tooltip" data-placement="left" title="" data-original-title="Agregar Producto">
      <i class="material-icons">add</i>
    </a>
  </div>
  

app/views/admin/brands/new.html.erb
<div class="row">
        <div class="col-md-10">
            <div class="card padding-largo">
                <div class="row">
                    <h3>Nueva Marca</h3>
                </div>
                <div class="row">
                    <%= render 'form',  brand: @brand %>
                </div>
                <div class="row">
                    <%= link_to 'Regresar', admin_brands_path %>
                </div>
            </div>
        </div>
    </div>
    
    

app/views/admin/brands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @brand.name %>
</p>

<%= link_to 'Edit', edit_brand_path(@brand) %> |
<%= link_to 'Back', brands_path %>