config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  

  get 'mis-compras/', to: "purchase#index"

  get 'checkout/', to: "checkout#index"
  get 'cart/', to: "cart#index"
  post 'payment/card'
  get 'payment/card'
  post 'payment/paypal'
  post 'payment/oxxo'
  resources :orders
  resources :cart_items
  namespace :admin do
    root 'welcome#index'
    resources :categories
    resources :products
    resources :brands
  end

  resources :categories
  resources :products
  resources :brands
  root 'welcome#index'

  # Namespace for the API

  # Api with subdomain, api.mysite.org as '/...'
    # namespace :api,
    #   defaults: { format: :json }, constraints: { subdomain: 'api' }, path: '/'  do
    # end

  # Api uri formated mysite.org/api/...
  namespace :api, defaults: { format: :json } do
    scope module: :v1,
              constraints: ApiConstraints.new(version: 1, default: true) do
      # We are going to list our resources here
    end
  end

  # Change path to '/' if you want direct access to users views
   # Device acces for the users
  devise_for :users, path: '/', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    unlocks: 'users/unlocks',
    omniauth: 'users/omniauth'
  }

  #spanish path for devise
  devise_scope :user do
    get 'iniciar-sesion', to: 'users/sessions#new'
    get 'cerrar-sesion', to: 'users/sessions#destroy', as: :sign_out

    get 'registro', to: 'users/registrations#new'
    post 'sign_up', to: 'users/registrations#create'

    get 'recuperar-contraseña', to: 'users/passwords#new'
    get 'recuperar-contrasena', to: 'users/passwords#new'
    get 'nueva-contraseña', to: 'users/passwords#edit'
    get 'nueva-contrasena', to: 'users/passwords#new'

    get 'solicitar-confirmacion', to: 'users/confirmations#new'
    get 'confirmar-cuenta', to: 'users/confirmations#show'
  end

end

app/models/category.rb
class Category < ApplicationRecord
	has_many :has_categories
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  @text = ""
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all.paginate(:page => params[:page], :per_page => 15)
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
    @text = "Crear Categoria"
  end

  # GET /categories/1/edit
  def edit
    @text = "Editar Categoria"
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_categories_path, notice: 'Se ha creado la categoria correctamente.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to admin_categories_path, notice: 'Se ha editado la categoria.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to admin_categories_url, notice: 'Se ha eliminado la categoria.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @products = []

     @category.has_categories.each do |c|
      @products.push(c)
    end

  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for([:admin,category]) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, "Nombre" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit @text, class: "btn btn-raised btn-info"%>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<div class="row">
        <div class="col-md-10">
            <div class="card padding-largo">
                <div class="row">
                    <h3>Editar Categoria</h3>
                </div>
                <div class="row">
                    <%= render 'form',  category: @category %>
                </div>
                <div class="row">
                    <%= link_to 'Regresar', admin_categories_path %>
                </div>
            </div>
        </div>
    </div>
    
    

app/views/admin/categories/index.html.erb
<div class="row">
    <div class="col-md-12">
      <div class="padding-largo">
        
        <div class="panel panel-info custom-panel">
        <div class="panel-heading">
          <h3 class="panel-title">Lista de categorias</h3>
        </div>
        <div class="panel-body">
          <table class="table table-striped table-hover">
            <thead></thead>
            <tbody>
              <%@categories.each do |p|%>
                <tr>
                  <td>
                    <%=p.name%>
                  </td>
  
                  <td>
                  <%= link_to 'Editar', edit_admin_category_path(p) %>
                  <%= link_to 'Eliminar', admin_category_path(p), method: :delete, data: { confirm: '¿Estas seguro de eliminarlo?' } %></td>
  
                </tr>
              <%end%>
            </tbody>
          </table>
  
          <div class="row">
            <div class="" style="margin: 0 auto;">
            <%= will_paginate @categorires, renderer: BootstrapPagination::Rails  %>
          </div>
          </div>
        </div>
      </div>
  
      </div>
    </div>
  </div>
  
  
  <div class="float-btn">
    <a href="/admin/categories/new" class="btn btn-info btn-fab accent-color" data-toggle="tooltip" data-placement="left" title="" data-original-title="Agregar Producto">
      <i class="material-icons">add</i>
    </a>
  </div>
  

app/views/admin/categories/new.html.erb
<div class="row">
        <div class="col-md-10">
            <div class="card padding-largo">
                <div class="row">
                    <h3>Nueva Categoria</h3>
                </div>
                <div class="row">
                    <%= render 'form',  category: @category %>
                </div>
                <div class="row">
                    <%= link_to 'Regresar', admin_categories_path %>
                </div>
            </div>
        </div>
    </div>
    
    

app/views/admin/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>