config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  

  get 'mis-compras/', to: "purchase#index"

  get 'checkout/', to: "checkout#index"
  get 'cart/', to: "cart#index"
  post 'payment/card'
  get 'payment/card'
  post 'payment/paypal'
  post 'payment/oxxo'
  resources :orders
  resources :cart_items
  namespace :admin do
    root 'welcome#index'
    resources :categories
    resources :products
    resources :brands
  end

  resources :categories
  resources :products
  resources :brands
  root 'welcome#index'

  # Namespace for the API

  # Api with subdomain, api.mysite.org as '/...'
    # namespace :api,
    #   defaults: { format: :json }, constraints: { subdomain: 'api' }, path: '/'  do
    # end

  # Api uri formated mysite.org/api/...
  namespace :api, defaults: { format: :json } do
    scope module: :v1,
              constraints: ApiConstraints.new(version: 1, default: true) do
      # We are going to list our resources here
    end
  end

  # Change path to '/' if you want direct access to users views
   # Device acces for the users
  devise_for :users, path: '/', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    unlocks: 'users/unlocks',
    omniauth: 'users/omniauth'
  }

  #spanish path for devise
  devise_scope :user do
    get 'iniciar-sesion', to: 'users/sessions#new'
    get 'cerrar-sesion', to: 'users/sessions#destroy', as: :sign_out

    get 'registro', to: 'users/registrations#new'
    post 'sign_up', to: 'users/registrations#create'

    get 'recuperar-contraseña', to: 'users/passwords#new'
    get 'recuperar-contrasena', to: 'users/passwords#new'
    get 'nueva-contraseña', to: 'users/passwords#edit'
    get 'nueva-contrasena', to: 'users/passwords#new'

    get 'solicitar-confirmacion', to: 'users/confirmations#new'
    get 'confirmar-cuenta', to: 'users/confirmations#show'
  end

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :brand
  has_many :has_categories
  after_create :save_categories
  mount_uploader :image, FotoUploader

  def categories=(vaue)
  	@categories=vaue
  end

  def save_categories
  	@categories.each do |cat|
  		HasCategory.create(category_id: cat, product_id: self.id)
  	end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all.paginate(:page => params[:page], :per_page => 15)
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @categories = Category.all
    @brands = Brand.all
  end

  # GET /products/1/edit
  def edit
    @categories = Category.all
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.categories = params[:categories]
    puts params[:categories]
    respond_to do |format|
      if @product.save
        format.html { redirect_to admin_product_path(@product), notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to admin_product_path(@product), notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :model, :price, :description, :brand_id,:image)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all.paginate(:page => params[:page], :per_page => 12)
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :model, :price, :description, :brand_id,:image)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_for([:admin,product], :html => {:multipart => true} ) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-3">
      <div class="form-group">
        <%= f.label :name, "Nombre" %>
        <%= f.text_field :name,class: 'form-control' %>
      </div>
    </div>
    <div class="col-md-3">
       <div class="form-group">
        <%= f.label :model,"Modelo"%>
        <%= f.text_field :model,class: 'form-control' %>
      </div>
    </div>
        <div class="col-md-3">
      <div class="form-group">
      <%= f.label :brand_id, "Marca", class: '' %>
      <select name="product[brand_id]" id="" class="form-control">
        <option value=""></option>
        <%@brands.each do |b|%>
          <option value="<%=b.id%>"><%=b.name%></option>
        <%end%>
      </select>
      
    </div>
    </div>
    <div class="col-md-3">
      <div class="form-group">
        <%= f.label :price, "Precio" %>
        <%= f.text_field :price,class: 'form-control' %>
      </div>
    </div>

  </div>
  
  <div class="row">
    <div class="col-md-12">
        <div class="form-group">
    <%= f.label :description, "Descripcion" %>
    <%= f.text_area :description,class: 'form-control' %>
  </div>

    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <label for="">Categorias</label>
        <%@categories.each do |cat|%>
          <%= check_box_tag "categories[]", cat.id%> <%= "#{cat.name}".upcase%>
        <%end%>
      </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <label for="">Seleccionar Imagen</label>
      <input id="inputFile4" multiple="" type="file">
      <div class="input-group">
        <%= f.file_field :image,class: 'form-control', placeholder: "Seleccionar Imagen" %>
          <span class="input-group-btn input-group-sm">
            <button type="button" class="btn btn-info btn-fab btn-fab-mini">
              <i class="material-icons">attach_file</i>
            </button>
          </span>
      </div>
    </div>

    </div>
  </div>

  <div class="row">
    <div class="col-md-3">
        <div class="actions">
          <%= f.submit "Crear producto" , class: "btn btn-raised btn-info"%>
        </div>
    </div>
  </div>


  


<% end %>

app/views/admin/products/edit.html.erb
<div class="row">
	<div class="col-md-10">
		<div class="card padding-largo">
			<div class="row">
				<h3>Editar Producto</h3>
			</div>
			<div class="row">
				<%= render 'form', product: @product %>
			</div>
			<div class="row">
				<%= link_to 'Regresar', products_path %>
			</div>
		</div>
	</div>
</div>

app/views/admin/products/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="padding-largo">
      
      <div class="panel panel-info custom-panel">
      <div class="panel-heading">
        <h3 class="panel-title">Lista de productos</h3>
      </div>
      <div class="panel-body">
        <table class="table table-striped table-hover">
          <thead></thead>
          <tbody>
            <%@products.each do |p|%>
              <tr>
                <td>
                  <%=p.name%>
                </td>
                <td>
                  <%=p.model%>
                </td>

               
                <td>
                  <%=p.price%>
                </td>

                <td>
                  <%=p.brand.name%>
                </td>

                <td>
                <%= link_to 'Ver', admin_product_path(p) %>
                <%= link_to 'Editar', edit_admin_product_path(p) %>
                <%= link_to 'Eliminar', admin_product_path(p), method: :delete, data: { confirm: '¿Estas seguro de eliminarlo?' } %></td>

              </tr>
            <%end%>
          </tbody>
        </table>

        <div class="row">
          <div class="" style="margin: 0 auto;">
          <%= will_paginate @products, renderer: BootstrapPagination::Rails  %>
        </div>
        </div>
      </div>
    </div>

    </div>
  </div>
</div>


<div class="float-btn">
  <a href="/admin/products/new" class="btn btn-info btn-fab accent-color" data-toggle="tooltip" data-placement="left" title="" data-original-title="Agregar Producto">
    <i class="material-icons">add</i>
  </a>
</div>

app/views/admin/products/new.html.erb
<div class="row">
	<div class="col-md-10">
		<div class="card padding-largo">
			<div class="row">
				<h3>Nuevo Producto</h3>
			</div>
			<div class="row">
				<%= render 'form', product: @product %>
			</div>
			<div class="row">
				<%= link_to 'Regresar', admin_products_path %>
			</div>
		</div>
	</div>
</div>

app/views/admin/products/show.html.erb
<div class="row">
  <div class="col-md-12">
    <ul class="breadcrumb" style="margin-bottom: 5px;">
    <li><%= link_to "Inicio", admin_root_path %></li>
    <li><%= link_to "Productos", admin_products_path %></li>
    <li class="active"><%= "#{@product.name}".upcase %></li>
  </ul>
  </div>
</div>

<div class="row" style="margin-top: 2em;">
  <div class="col-md-12">
    <div class="card">
      <div class="row">
        <div class="col-md-4">

          <img src="<%=@product.image.url%>" alt="" class="img-responsive" style="margin-left: -1.1em;">
        </div>
        <div class="col-md-8" >
          <div class="row">
            <h3><%= @product.name %></h3>
          </div>
          <div class="row">
            <p class="sub-header">Modelo: <%= @product.model %> <span style="margin-left: 2em;">Marca: <%= @product.brand.name %></span> </p>
            <p class="price"> $ <%= @product.price %></p>
            <p class="desc">
              <%= @product.description %>
            </p>
            <p class="categories">
            <ul class="nav nav-pills">
            <% @product.has_categories.each do |has_category| %>
                <li class="active"><a href="javascript:void(0)"><%= "#{has_category.category.name}".upcase%></span></a></li>
              <%end%>
              
            </ul>
              
            </p>
          </div>
          <div class="row">
            <%= link_to "Editar", edit_admin_product_path(@product), class: 'btn btn-raised btn-success '%>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>